[package]
name = "tudo"
version = "0.1.0"
edition = "2021"
description = "Todo tui app written in Rust"
authors = ["Nikodem Marek <nikodemmarek11@gmail.com>"]

[dependencies]
tui = "0.19.0"
crossterm = "0.25"
